name: kmotion

volumes:
  database:

networks:
  kmotion-net:
    name: kmotion-net
    driver: bridge

services:
  database:
    image: postgres:17.6
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      kmotion-net:
    ports:
      - "3032:5432"
    volumes:
      - database:/var/lib/postgresql/data
      - ./.docker/database:/docker-entrypoint-initdb.d
