@musicId = c46642a8-9818-41c8-9847-54d838b351dd
@playlistId = 4ccad19f-a4f2-460a-aa84-1ce16e53a00b

POST {{baseURL}}/auth/register
Content-Type: application/json

{
  "email": "{{$random.email}}",
  "name": "{{$random.name.fullName}}",
  "password": "password123"
}

> {%
  client.global.set('token', response.body);
%}


### Auth : Login
POST {{baseURL}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "password123"
}


> {%
  client.global.set('token', response.body);
%}

### User : Get profile
GET {{baseURL}}/users/me
Authorization: Bearer {{token}}
Content-Type: application/json

> {%
  client.global.set('id', response.body.id);
  client.global.set('slug', response.body.slug);
%}

### User : Find By ID
GET {{baseURL}}/users/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

### User : Finy By Slug
GET {{baseURL}}/users/slug/{{slug}}
Authorization: Bearer {{token}}
Content-Type: application/json

### User : Index
GET {{baseURL}}/users?offset=1&size=1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json


### Music : Sync
POST {{baseURL}}/musics/sync
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: text/plain

### Musics : Index
GET {{baseURL}}/musics?page=0&size=20
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json


### Music : Download
POST {{baseURL}}/musics
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: text/plain

{
  "mediaId": "tswOoVlIA5Q",
  "mediaSource": "youtube"
}

### Music : Search
GET {{baseURL}}/musics/search?query=il v
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

### Music : Get By Id
GET {{baseURL}}/musics/{{musicId}}
Authorization: Bearer {{token}}

### Music : Fetch thunbnail
GET {{baseURL}}/musics/{{musicId}}/thumbnail
Authorization: Bearer {{token}}

### Music : Fetch thunbnail
GET {{baseURL}}/musics/{{musicId}}/audio
Authorization: Bearer {{token}}

### Music : Get By Media
GET {{baseURL}}/musics/media/a13ffqJgH78?source=youtube
Authorization: Bearer {{token}}

### Playlist : Create
POST {{baseURL}}/playlists
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "{{$random.commerce.productName}}",
  "description": "{{$random.lorem.paragraph}}",
  "visibility": "private",
  "entries": [
    { "musicId": "{{musicId}}", "position": 1 }
  ]
}

### Playlist : Index
GET {{baseURL}}/playlists?page=0&size=20
Authorization: Bearer {{token}}
Content-Type: application/json

### Playlist : Show
GET {{baseURL}}/playlists/{{playlistId}}
Authorization: Bearer {{token}}
Content-Type: application/json

### Playlist : Update
PATCH {{baseURL}}/playlists/{{playlistId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Ma Super Playlist Modifiée",
  "description": "Nouvelle description"
}

### Playlist : Delete
DELETE {{baseURL}}/playlists/{{playlistId}}
Authorization: Bearer {{token}}
Content-Type: application/json

### Playlist : Add Music
POST {{baseURL}}/playlists/{{playlistId}}/musics
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "musicId": "{{musicId}}",
  "position": 2
}

### Playlist : Remove Music
DELETE {{baseURL}}/playlists/{{playlistId}}/musics/{{musicId}}
Authorization: Bearer {{token}}
Content-Type: application/json

### Playlist : Show by user id
GET {{baseURL}}/playlists/users/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

### Plalist: Add entry to playlist
POST {{baseURL}}/playlists/{{playlistId}}/musics
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "musicId": "a222216b-ed85-4b0c-bc75-dc47dbba87a1",
  "position": 1
}
