@musicId = 6a116c36-e920-4dee-88ba-532a9c98841d

POST {{baseURL}}/auth/register
Content-Type: application/json

{
  "email": "{{$random.email}}",
  "name": "{{$random.name.fullName}}",
  "password": "password123"
}

> {%
  client.global.set('token', response.body);
%}


### Auth : Login
POST {{baseURL}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "password123"
}


> {%
  client.global.set('token', response.body);
%}

### User : Get profile
GET {{baseURL}}/users/me
Authorization: Bearer {{token}}
Content-Type: application/json

> {%
  client.global.set('id', response.body.id);
  client.global.set('slug', response.body.slug);
%}

### User : Find By ID
GET {{baseURL}}/users/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

### User : Finy By Slug
GET {{baseURL}}/users/slug/{{slug}}
Authorization: Bearer {{token}}
Content-Type: application/json

### User : Index
GET {{baseURL}}/users?offset=1&size=1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json


### Music : Sync
POST {{baseURL}}/musics/sync
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: text/plain

### Musics : Index
GET {{baseURL}}/musics?page=0&size=20
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json


### Music : Download
POST {{baseURL}}/musics
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: text/plain

{
  "mediaId": "tswOoVlIA5Q",
  "mediaSource": "youtube"
}

### Music : Search
GET {{baseURL}}/musics/search?query=il v
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

### Music : Get By Id
GET {{baseURL}}/musics/{{musicId}}
Authorization: Bearer {{token}}

### Music : Fetch thunbnail
GET {{baseURL}}/musics/{{musicId}}/thumbnail
Authorization: Bearer {{token}}

### Music : Fetch thunbnail
GET {{baseURL}}/musics/{{musicId}}/audio
Authorization: Bearer {{token}}

### Music : Get By Media
GET {{baseURL}}/musics/media/a13ffqJgH78?source=youtube
Authorization: Bearer {{token}}
