apiVersion: v1
kind: ConfigMap
metadata:
  name: app
  namespace: kmotion
data:
  PORT: "80"
  NODE_ENV: production
  API_URL: https://kmotion.thomasgleizes.fr/api
  CLIENT_URL: https://kmotion.thomasgleizes.fr
  DOMAIN: kmotion.thomasgleizes.fr
  CONVERTER_KEY: YxSn9ROYVgesVbrtoM04cuMPdp0GXF9i
  CONVERTER_URL: http://app.ytc
  SECRET_SEED: ""
  SECRET_SESSION: ""
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: appdb
  DB_USER: postgres
