apiVersion: v1
kind: ConfigMap
metadata:
  name: app
  namespace: kmotion
data:
  PORT: "80"
  NODE_ENV: production
  API_URL: https://kmotion.thomasgleizes.fr/api
  CLIENT_URL: https://kmotion.thomasgleizes.fr
  DOMAIN: kmotion.thomasgleizes.fr
  PASSWORD_PAPER: Npjkyd6YkD01erQMxGhdsxT0TecxNmwG
  CONVERTER_TOKEN: 7bLFvjgzOM2nOqYM5L7OFpBPSEl25ukN
  CONVERTER_URL: http://ytc.app
  SECRET_SEED: ""
  SECRET_SESSION: ""
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: appdb
  DB_USER: postgres
